version: '3.9'

services:
  postgres:
    image: postgres:14.4
    container_name: indie-hub
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indiehub-db